blank_issues_enabled: false
contact_links:
  - name: Question or usage help
    url: https://github.com/brightio/penelope/discussions
    about: For usage questions and general discussion, please use Discussions.
